import type { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiCalendar,
  HiCheck,
  HiCheckCircle,
  HiChevronDown,
  HiChevronLeft,
  HiChevronRight,
  HiChevronUp,
  HiChevronUpDown,
  HiComputerDesktop,
  HiExclamationCircle,
  HiExclamationTriangle,
  HiEyeDropper,
  HiInformationCircle,
  HiMiniMinus,
  HiMiniPlus,
  HiMiniQuestionMarkCircle,
  HiMiniUser,
  HiMiniXMark,
  HiOutlineArrowPath,
  HiOutlineClipboard,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineLink,
  HiOutlineMagnifyingGlass,
  HiOutlineMoon,
  HiOutlineShieldCheck,
  HiOutlineSparkles,
  HiOutlineSun,
} from "react-icons/hi2";

import { RiVisaLine } from "react-icons/ri";

import { FaDiscord, FaGithub, FaGoogle } from "react-icons/fa6";
import {
  LuImage as LucideImage,
  LuFileText as LucideFileText,
  LuVideo as LucideVideo,
  LuMusic as LucideMusic,
  LuArchive as LucideArchive,
  LuCode as LucideCode,
  LuFile as LucideFile,
} from "react-icons/lu";

import {
  TbHome,
  TbUsersGroup,
  TbDatabase,
  TbFolder,
  TbMessage,
  TbTerminal,
  TbTableSpark,
  TbLambda,
  TbLayoutDashboard,
  TbUsers,
  TbGraph,
  TbReceiptDollar,
  TbSettings,
  TbTable,
  TbMail,
  TbMessages,
  TbNotification,
  TbLayersDifference,
  TbRocket,
  TbKey,
  TbLogs,
  TbTextRecognition,
  TbHash,
  TbToggleLeft,
  TbList,
  TbLink,
  TbBrandMailgun,
  TbArrowGuide,
  TbCalendar,
  TbGlobe,
  TbTableAlias,
  TbBrandReactNative,
  TbBrandFlutter,
  TbBrandApple,
  TbBrandAndroid,
} from "react-icons/tb";
import { Edit3, ExternalLink, Trash2 } from "lucide-react";
import { CgArrowLongRightC, CgArrowsH } from "react-icons/cg";

export const iconMap = {
  chevronUp: HiChevronUp,
  chevronDown: HiChevronDown,
  chevronsUpDown: HiChevronUpDown,
  chevronRight: HiChevronRight,
  chevronLeft: HiChevronLeft,
  refresh: HiOutlineArrowPath,
  check: HiCheck,
  light: HiOutlineSun,
  dark: HiOutlineMoon,
  helpCircle: HiMiniQuestionMarkCircle,
  infoCircle: HiInformationCircle,
  warningTriangle: HiExclamationTriangle,
  errorCircle: HiExclamationCircle,
  checkCircle: HiCheckCircle,
  eyeDropper: HiEyeDropper,
  clipboard: HiOutlineClipboard,
  person: HiMiniUser,
  close: HiMiniXMark,
  openLink: HiOutlineLink,
  discord: FaDiscord,
  google: FaGoogle,
  github: FaGithub,
  arrowUpRight: HiArrowUpRight,
  minus: HiMiniMinus,
  plus: HiMiniPlus,
  calendar: HiCalendar,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  search: HiOutlineMagnifyingGlass,
  visa: RiVisaLine,
  security: HiOutlineShieldCheck,
  sparkle: HiOutlineSparkles,
  rocket: TbRocket,
  house: TbHome,
  edit: Edit3,
  externalLink: ExternalLink,
  tableEditor: TbTableSpark,
  table: TbTable,
  collectionEditor: TbTableAlias,
  storage: TbFolder,
  database: TbDatabase,
  messaging: TbMessage,
  runner: TbTerminal,
  authentication: TbUsersGroup,
  functions: TbLambda,
  nuvixSchemas: TbLayersDifference,
  key: TbKey,
  logs: TbLogs,
  trash: Trash2,
  // File type icons
  image: LucideImage,
  document: LucideFileText,
  video: LucideVideo,
  audio: LucideMusic,
  archive: LucideArchive,
  code: LucideCode,
  file: LucideFile,
  computer: HiComputerDesktop,

  // Org Page
  projects: TbLayoutDashboard,
  members: TbUsers,
  usage: TbGraph,
  billing: TbReceiptDollar,

  settings: TbSettings,

  mail: TbMail,
  sms: TbMessages,
  push: TbNotification,

  // attributes
  string: TbTextRecognition,
  integer: TbHash,
  float: TbHash,
  boolean: TbToggleLeft,
  enum: TbList,
  url: TbLink,
  email: TbBrandMailgun,
  relationship: TbArrowGuide,
  timestamptz: TbCalendar,
  ip: TbGlobe,
  oneWay: CgArrowLongRightC,
  twoWay: CgArrowsH,

  // platform
  reactNative: TbBrandReactNative,
  flutter: TbBrandFlutter,
  apple: TbBrandApple,
  android: TbBrandAndroid,
} as const;

export type IconName = keyof typeof iconMap;
export type IconLibrary = Record<IconName, IconType>;
export const iconLibrary: IconLibrary = iconMap;
